#----------------갈증-------------------
물 다는 속도 : 120 #tick

갈증 구속 지속시간 : 10 #tick
갈증 구속 레벨 : 2

갈증 멀미 지속시간 : 10 #tick
갈증 멀미 레벨 : 3

갈증 독 지속시간 : 10 #tick
갈증 독 레벨 : 2

#----------------스태미나-------------------
스태미나 구속 지속시간 : 7 #tick

스태미나 구속 레벨 : 6
스태미나 다는 속도 : 2 #tick

도구 사용 시 스태미나 다는 속도 : 1

